works = {
    id: 1,
    name: 'Multi-Post Stories',
    img: "./images/img work alone.png",
    altImg: "Image of my project",
    description: `A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.`,
    tech: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
    projectLink: '*',
    demoLink: '*',

    id: 2,
    name: 'Profesional Art Printing Data',
    img: "./images/img work alone.png",
    altImg: "Image of my project",
    description: `A daily selection of privately personalized reads; no accounts or sign-ups required. Has been the industry's standard.`,
    tech: ['HTML', 'Bootstrap', 'Ruby'],
    projectLink: '*',
    demoLink: '*',

    id: 3,
    name: 'Profesional Art Printing Data More',
    img: "./images/img work alone.png",
    altImg: "Image of my project",
    description: `A daily selection of privately personalized reads; no accounts or sign-ups required. Has been the industry's standard.`,
    tech: ['HTML', 'Bootstrap', 'Ruby'],
    projectLink: '*',
    demoLink: '*',

    id: 4,
    name: 'Data Dashboard Healthcare',
    img: "./images/img work alone.png",
    altImg: "Image of my project",
    description: `A daily selection of privately personalized reads; no accounts or sign-ups required. Has been the industry's standard.`,
    tech: ['HTML', 'Bootstrap', 'Ruby'],
    projectLink: '*',
    demoLink: '*',

    id: 5,
    name: 'Data Dashboard Healthcare',
    img: "./images/img work alone.png",
    altImg: "Image of my project",
    description: `A daily selection of privately personalized reads; no accounts or sign-ups required. Has been the industry's standard.`,
    tech: ['HTML', 'Bootstrap', 'Ruby'],
    projectLink: '*',
    demoLink: '*',

    id: 6,
    name: 'Data Dashboard Healthcare',
    img: "./images/img work alone.png",
    altImg: "Image of my project",
    description: `A daily selection of privately personalized reads; no accounts or sign-ups required. Has been the industry's standard.`,
    tech: ['HTML', 'Bootstrap', 'Ruby'],
    projectLink: '*',
    demoLink: '*',
}
